credentials:
  usernames:
    audrey:
      email: audrey@gmail.com
      name: audrey
    william:
      email: William@gmail.com
      name: william
    admin:
      email: admin@gmail.com
      name: admin
cookie:
  name: conecta_unicamacho
  key:  conecta_unicamacho
  expiry_days: 0.002